services:
  postgres:
    image: postgres:15
    container_name: job-tracker-db
    environment:
      POSTGRES_DB: job_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - job-tracker-network

  redis:
    image: redis:7-alpine
    container_name: job-tracker-redis
    ports:
      - "6379:6379"
    networks:
      - job-tracker-network

volumes:
  pgdata:

networks:
  job-tracker-network:
    driver: bridge 